Controllers films users
prokman/java-filmorate pull request #1
Opened 2024-12-06 18:15 UTC by prokman

Реализовано ТЗ-10

2024-12-07 18:55 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-12-07 18:55 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Map<Integer, Film> films = new HashMap<>();
Лучше было бы разделить контроллер и хранение данных в разные классы, так было бы проще тестировать, код был бы чище и понятнее

2024-12-07 18:55 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        int currentMaxId = users.keySet()
Сейчас очень долго получать id, лучше завести счётчик просто

2024-12-07 18:55 UTC, mikita95 commented on pom.xml
> +			<version>2.0.16</version>
Номера версий можно было бы вынести в свойства pom файла, так было бы проще ими управлять

2024-12-08 12:04 UTC, prokman commented on pom.xml
> +			<version>2.0.16</version>
Учтено

2024-12-08 12:04 UTC, prokman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        int currentMaxId = users.keySet()
Учтено

2024-12-08 12:04 UTC, prokman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Map<Integer, Film> films = new HashMap<>();
Учтено

2024-12-09 09:13 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-12-09 15:51 UTC, merged