Add friends likes
prokman/java-filmorate pull request #2
Opened 2024-12-31 10:44 UTC by prokman

ТЗ 11 реализовано. С новым Годом!!! всего наилучшего в новом году, успехов в работе, счастья в семье, а в отпуск обязательно на высокие горы и синие моря!!!

2024-12-31 11:37 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-12-31 11:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/repository/InMemoryUserStorage.java
> +    public InMemoryUserStorage(Map<Integer, User> users, Map<Integer, Set<User>> friends, Set<User> setOfFriends) {
Это не бины, их не нужно инжектить

2024-12-31 11:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService() {
Этот конструктор тогда не нужен...

2024-12-31 11:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Здесь лучше работать только с интерфейсами, а не реализациями

2024-12-31 12:30 UTC, prokman commented on src/main/java/ru/yandex/practicum/filmorate/repository/InMemoryUserStorage.java
> +    public InMemoryUserStorage(Map<Integer, User> users, Map<Integer, Set<User>> friends, Set<User> setOfFriends) {
учтено

2024-12-31 12:30 UTC, prokman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService() {
учтено

2024-12-31 12:30 UTC, prokman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
учтено

2025-01-01 12:00 UTC, mikita95 approved these changes
Все сделано отлично :) Можно мержить пул-реквест. И Вас с Новым Годом!

2025-01-02 15:38 UTC, merged